apiVersion: v1
kind: ConfigMap
metadata:
  name: project-configmap
  namespace: project
data:
  CACHE_IMAGE: /shared/image.jpg
  CACHE_TIMESTAMP: /shared/timestamp.txt
  TODO_BACKEND_URL: http://backend-service:1345/todos
  IMAGE_SOURCE_URL: https://picsum.photos/1200



