apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: project-route
  namespace: project
  metadata:
  labels:
    app: project-route
spec:
  parentRefs:
  - name: project-gateway
  rules:
  - matches:
      - path:
          type: PathPrefix
          value: /
    backendRefs:
      - name: project-svc
        port: 1234
