apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-todo-generator
  namespace: project
  labels:
    app: random-todo-generator
spec:
  schedule: "0 * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-generator
            image: alpine:latest
            command: ["/bin/sh", "-c"]
            args:
              - |

                apk add --no-cache curl

                URL=$(curl -sI https://en.wikipedia.org/wiki/Special:Random | grep -i location | awk '{print $2}' | tr -d '\r');

                TODO="Read $URL";

                # Post to backend
                curl -X POST -H "Content-Type: application/json" \
                  -d "{\"content\": \"${TODO}\"}" \
                  "$TODO_BACKEND_URL";
            env:
            - name: TODO_BACKEND_URL
              value: "http://backend-service:1345/todos"
          restartPolicy: OnFailure
