apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - StatefulSet.yaml
  - config.yaml
  - cronjob.yaml
  - cronjob_2.yaml
  - deployment.yaml
  - namespace.yaml
  - service.yaml
